spring:
  application:
    name: cf-kaizen-hoover-server

  ai:
    mcp:
      server:
        name: ${spring.application.name}
        stdio: true

  jackson:
    default-property-inclusion: non_null

  main:
    banner-mode: off
    web-application-type: none

  threads:
    virtual:
      enabled: true

management:
  info:
    build:
      enabled: true
    git:
      mode: FULL
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,metrics,loggers,sbom

default:
  url: ${CF_HOOVER_API_ENDPOINT}

logging:
  pattern:
    console:
  file:
    name: ${user.home}/logs/cf-kaizen-hoover-client.log

---

spring:
  config:
    activate:
      on-profile: cloud

  main:
    banner-mode: log
    web-application-type: reactive

  ai:
    mcp:
      server:
        stdio: false
        type: ASYNC

logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"

---

spring:
  config:
    activate:
      on-profile: dev

debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8084