spring:
  application:
    name: cf-kaizen-butler-client

  ai:
    mcp:
      server:
        enabled: true
        name: ${spring.application.name}
        version: 1.0.0
        stdio: true

  jackson:
    default-property-inclusion: non_null

  main:
    banner-mode: off
    web-application-type: none

  threads:
    virtual:
      enabled: true

management:
  info:
    build:
      enabled: true
    git:
      mode: FULL
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,metrics,loggers,sbom

default:
  url: ${CF_BUTLER_API_ENDPOINT:}

accounting:
  url: ${default.url}
onDemand:
  url: ${default.url}
policies:
  url: ${default.url}
products:
  url: ${default.url}
snapshot:
  url: ${default.url}

logging:
  pattern:
    console:
  file:
    name: ${user.home}/logs/cf-kaizen-butler-client.log

---

spring:
  config:
    activate:
      on-profile: cloud

  main:
    banner-mode: log
    web-application-type: servlet

logging:
  pattern:
    console: "%style{%d{ISO8601}}{black} %highlight{%-5level }[%style{%t}{bright,blue}] %style{%c{1.}}{bright,yellow}: %msg%n%throwable"

---

spring:
  config:
    activate:
      on-profile: dev

debug: true

default:
  url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8088