---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uaa-tls-cert
  namespace: uaa
spec:
  secretName: uaa-tls-secret
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - UAA
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - uaa-127-0-0-1.nip.io
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
