---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uaa
  namespace: uaa
  labels:
    app.kubernetes.io/name: uaa
    app.kubernetes.io/component: authorization_server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: uaa
      app.kubernetes.io/component: authorization_server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: uaa
        app.kubernetes.io/component: authorization_server
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9102'
        prometheus.io/path: '/metrics'
    spec:
      serviceAccountName: uaa
      containers:
        - name: uaa
          image: cloudfoundry/uaa:77.25.0@sha256:677480cd88dc27bd88d2dc020c8ed640a600d6250b3b0f1f33b0c2d2d613b9e8
          resources:
            requests:
              memory: "512Mi"
              cpu: "50m"
            limits:
              memory: "2000Mi"
              cpu: "500m"
          ports:
            - name: http-uaa
              containerPort: 8080
              protocol: TCP
          env:
            - name: BPL_TOMCAT_ACCESS_LOGGING
              value: "y"
            - name: JAVA_OPTS
              value: >-
                -Dspring_profiles=hsqldb
                -Djava.security.egd=file:/dev/./urandom
                -Dlogging.config=/etc/config/log4j2.properties
                -Dlog4j.configurationFile=/etc/config/log4j2.properties
                -DCLOUDFOUNDRY_CONFIG_PATH=/etc/config
                -DSECRETS_DIR=/etc/secrets
                -Dstatsd.enabled=true
                -Dservlet.session-store=database
          volumeMounts:
            - name: uaa-config
              mountPath: /etc/config
            - name: uaa-secrets
              mountPath: /etc/secrets
          livenessProbe:
            httpGet:
              path: /healthz
              port: http-uaa
            failureThreshold: 25
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: http-uaa
        - name: statsd-exporter
          image: "cloudfoundry/statsd_exporter:v0.15.0@sha256:10a64dc4ad0a3e3fe88372f0481dea5c02595c38d168617836a99a649d3ac407"
          imagePullPolicy: Always
          args: ["--statsd.listen-udp=:8125"]
          ports:
            - name: "metrics-uaa"
              containerPort: 9102
              protocol: "TCP"
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"
      volumes:
        - name: uaa-config
          configMap:
            name: uaa-config
        - name: uaa-secrets
          secret:
            secretName: uaa-secrets
