#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: uaa-secrets
  namespace: uaa
  labels:
    app.kubernetes.io/name: uaa
    app.kubernetes.io/component: authorization_server
type: Opaque
stringData:
  admin_client_credentials.yml: |
    oauth:
      clients:
        admin:
          secret: #@ data.values.admin_client_secret
  jwt_policy_signing_keys.yml: |
    jwt:
      token:
        policy:
          activeKeyId: jwt-key
          keys:
            jwt-key:
              signingAlg: RS256
              signingKey: #@ data.values.jwt_private_key
  saml_keys.yml: |
    login:
      saml:
        serviceProviderKey: #@ data.values.saml_private_key
        serviceProviderCertificate: #@ data.values.saml_certificate
        activeKeyId: "saml-key"
        keys:
          saml-key:
            key: #@ data.values.saml_private_key
            certificate: #@ data.values.saml_certificate
