#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def oauth():
oauth:
  clients:
    admin:
      secret: #@ data.values.admin_client_secret
    cf:
      secret: cloudcontroller
#@ end

#@ def jwt():
jwt:
  token:
    policy:
      activeKeyId: jwt-key
      keys:
        jwt-key:
          signingKey: #@ data.values.jwt_private_key
          signingAlg: RS256
#@ end

#@ def saml():
login:
  saml:
    serviceProviderKey: #@ data.values.saml_private_key
    serviceProviderCertificate: #@ data.values.saml_certificate
    activeKeyId: "saml-key"
    keys:
      saml-key:
        key: #@ data.values.saml_private_key
        certificate: #@ data.values.saml_certificate
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: uaa-secrets
  namespace: uaa
  labels:
    app.kubernetes.io/name: uaa
    app.kubernetes.io/component: authorization_server
type: Opaque
stringData:
  admin_client_credentials.yml: #@ yaml.encode(oauth())
  jwt_policy_signing_keys.yml: #@ yaml.encode(jwt())
  saml_keys.yml: #@ yaml.encode(saml())
