---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: uaa
  namespace: uaa
  labels:
    app.kubernetes.io/name: uaa
    app.kubernetes.io/component: authorization_server
automountServiceAccountToken: false
