---
apiVersion: v1
kind: Service
metadata:
  name: uaa
  namespace: uaa
  labels:
    app.kubernetes.io/name: uaa
    app.kubernetes.io/component: authorization_server
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31000
      targetPort: http-uaa
      protocol: TCP
      name: http-uaa
  selector:
    app.kubernetes.io/name: uaa
    app.kubernetes.io/component: authorization_server