apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-uaa-config
  labels:
    {{- include "uaa.labels" . | nindent 4 }}
data:
  uaa.yml: |
    {{- $values := .Values -}}
    issuer:
      uri: {{ $values.issuer.uri }}
    database:
      maxactive: 100
      maxidle: 10
      minidle: 0
      removeabandoned: false
      logabandoned: true
      abandonedtimeout: 300
      url: {{ $values.database.url }}
    smtp:
      host: {{ $values.smtp.host }}
      port: {{ $values.smtp.port }}
      starttls: {{ $values.smtp.starttls }}
      from_address: {{ $values.smtp.from_address }}
      sslprotocols: {{ $values.smtp.sslprotocols }}
    oauth:
      client:
        override: true
      clients:
        admin:
          authorized-grant-types: client_credentials
          authorities: "clients.read,clients.write,clients.secret,uaa.admin,scim.read,scim.write,password.write"
  log4j2.properties: |
    {{- .Files.Get "templates/log4j2.properties" | nindent 4 }}