apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "uaa.labels" . | nindent 4 }}
data:
  uaa.yml: |
    {{- with .Values }}
    issuer:
      uri: {{ .issuer.uri }}
    database:
      maxactive: 100
      maxidle: 10
      minidle: 0
      removeabandoned: false
      logabandoned: true
      abandonedtimeout: 300
      url: {{ .database.url }}
    smtp:
      host: {{ .smtp.host }}
      port: {{ .smtp.port }}
      starttls: {{ .smtp.starttls }}
      from_address: {{ .smtp.from_address }}
      sslprotocols: {{ .smtp.sslprotocols }}
    oauth:
      client:
        override: true
      clients:
        admin:
          authorized-grant-types: client_credentials
          authorities: "clients.read,clients.write,clients.secret,uaa.admin,scim.read,scim.write,password.write"
    {{- end }}
  log4j2.properties: |
    {{- .Files.Get "files/log4j2.properties" | nindent 4 }}