{{/*
Generate secrets for UAA.  This template creates multiple Secret resources.
*/}}

{{- $values := .Values -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-admin-client-credentials
  labels:
    {{- include "uaa.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin_client_credentials.yml: |
    oauth:
      clients:
        admin:
          secret: {{ $values.admin.client_secret }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt-policy-signing-keys
  labels:
    {{- include "uaa.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt_policy_signing_keys.yml: |
    jwt:
      token:
        policy:
          activeKeyId: {{ $values.jwt.policy.activeKeyId }}
          keys:
            {{ $values.jwt.policy.activeKeyId }}:
              signingAlg: {{ $values.jwt.policy.keys.signingAlg | default "RS256" }}
              signingKey: |-
                {{ $values.jwt.policy.keys.signingKey }}
              {{- if $values.jwt.policy.keys.signingCert }}
              signingCert: |-
                {{ $values.jwt.policy.keys.signingCert }}
              {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-saml-keys
  labels:
    {{- include "uaa.labels" . | nindent 4 }}
type: Opaque
stringData:
  saml_keys.yml: |
    login:
      saml:
        serviceProviderKey: |-
          {{ $values.login.saml.serviceProviderKey }}
        serviceProviderCertificate: |-
          {{ $values.login.saml.serviceProviderCertificate }}
        activeKeyId: {{ $values.login.saml.activeKeyId }}
        keys:
          {{ $values.login.saml.activeKeyId }}:
            signingKey: |-
              {{ $values.login.saml.keys.saml-key.signingKey }}
            {{- if $values.login.saml.keys.saml-key.certificate }}
            certificate: |-
              {{ $values.login.saml.keys.saml-key.certificate }}
            {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-encryption-keys
  labels:
    {{- include "uaa.labels" . | nindent 4 }}
type: Opaque
stringData:
  encryption_keys.yml: |
    encryption:
      active_key_label: {{ $values.encryption.active_key_label }}
      encryption_keys:
      {{- range $values.encryption.encryption_keys }}
        - label: {{ .label }}
          passphrase: {{ .passphrase }}
          encryptionKey: {{ .encryptionKey}}
      {{- end }}


{{- if or $values.database.username $values.database.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-credentials
  labels:
    {{- include "uaa.labels" . | nindent 4 }}
type: Opaque
stringData:
  database_credentials.yml: |
    database:
      username: {{ $values.database.username }}
      password: {{ $values.database.password }}
{{- end }}

{{- if or $values.smtp.user $values.smtp.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-smtp-credentials
  labels:
    {{- include "uaa.labels" . | nindent 4 }}
type: Opaque
stringData:
  smtp_credentials.yml: |
    smtp:
      user:  {{ $values.smtp.user }}
      password: {{ $values.smtp.password }}
{{- end }}

{{- if $values.ca_certs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ca-certs
  labels:
    {{- include "uaa.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $i := 0 }}
  {{- range $values.ca_certs }}
  uaa-ca-cert{{ $i }}.pem: {{ . | b64enc }}
    {{- $i = add1 $i }}
  {{- end }}
{{- end }}