apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "uaa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-uaa
      protocol: TCP
      name: http-uaa
  selector:
    app: uaa-deployment
    {{- include "uaa.selectorLabels" . | nindent 4 }}